### ISSUE TITLE
[Feat.]: Value枚举实现中缺少方法

### ISSUE THREAD

**Issue by lwclover** [oceanbase/obkv-table-client-rs#26]
### Check Before Asking

- [X] Please check the issue list and confirm this feature is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Description

```markdown
为什么在Value枚举实现中没有pub fn as_f64(&self) -> f64方法
```

**Comment by IHEII** [comment]
Because we do not need to convert double values now, it has not been implemented for the time being
